# Generated by Django 5.0 on 2023-12-17 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cards_s')),
            ],
        ),
    ]
