# Generated by Django 5.0 on 2023-12-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_card_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_detail',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
