# Generated by Django 5.0 on 2023-12-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_card_detail_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards_s',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cards_s',
            name='foto',
        ),
        migrations.AlterField(
            model_name='cards_s',
            name='name',
            field=models.CharField(max_length=350),
        ),
    ]
