# Generated by Django 5.0 on 2023-12-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cards_s_brand_remove_cards_s_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_detail',
            name='foto1',
            field=models.URLField(blank=True, null=True),
        ),
    ]
